# Configuration Settings for C94-M8P device
ublox_gps_node:
  ros__parameters:
    debug: 0                    # Range 0-4 (0 means no debug statements will print)
    config_in_startup: false
    device: /dev/ttyACM1
    frame_id: base_link
    uart1:
      baudrate: 230400
    # TMODE3 Config
    dgnss_mode: 2                  # Survey-In Mode
    fix_mode: 3d

    inf:
      all: true                   # Whether to display all INF messages in console
    
    publish:
      all: true
      posllh: true
      posecef: true
      esf:
        meas: true
      aid:
        hui: false
      nav:
        posecef: false
